In [110]:
import numpy as np
import string
import matplotlib.pyplot as plt
import csv
import pandas as pd

In [111]:
def normalize_words(text):
    words = text.split()
    norm_words = []
    for word in words:
        lastChar = len(word) - 1 
        if word[0] in ("#","@","(","$","'", '"') or word[0].isdigit():
            continue
        if word[lastChar].isdigit() or (word[lastChar] in string.punctuation):
            continue
        norm_words.append(word.lower().rstrip(string.punctuation))
    return norm_words

In [112]:
fulltxt = []
for x in range(85):
    filename = '/data/federalist/' + str(x+1) + '.txt'
    with open(filename, 'r') as myfile:
        data = myfile.read().replace('\n', ' ')
        data = normalize_words(data)
        
    fulltxt = fulltxt + data

In [113]:
vocab = {}
for word in fulltxt:
    if word not in vocab:
        vocab[word] = 1
    else:
        vocab[word] += 1

In [114]:
df = pd.Series(vocab)
df=df[df>25]

In [115]:
authors=pd.read_csv("/data/federalist/authorship.csv")

In [116]:
DF=pd.DataFrame(columns=df.index)

In [117]:
for x in range(85):
    filename = '/data/federalist/' + str(x+1) + '.txt'
    with open(filename, 'r') as myfile:
        data = myfile.read().replace('\n', ' ')
        data = normalize_words(data)
        
    article = pd.DataFrame(columns = df.index)
    article.loc[x] = 0
    for word in data:
        if word not in df.index:
            continue
        article[word] = article[word] + 1
        
    DF = DF.append(article)
DF.index = range(1,len(DF)+1)

In [118]:
DF=DF.reset_index()

In [119]:
DF

index      a  able  about  absolute  according  act  acts  actual  \
0       1   25.0   1.0    0.0       0.0        0.0  1.0   0.0     0.0   
1       2   29.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
2       3   13.0   1.0    0.0       0.0        0.0  1.0   0.0     0.0   
3       4   16.0   0.0    0.0       2.0        0.0  1.0   0.0     0.0   
4       5    9.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
5       6   52.0   0.0    0.0       0.0        1.0  0.0   0.0     1.0   
6       7   48.0   2.0    1.0       0.0        0.0  0.0   1.0     2.0   
7       8   45.0   2.0    0.0       1.0        0.0  0.0   0.0     0.0   
8       9   46.0   3.0    0.0       1.0        0.0  0.0   0.0     0.0   
9      10   78.0   2.0    0.0       0.0        3.0  3.0   1.0     0.0   
10     11   69.0   4.0    1.0       0.0        0.0  0.0   0.0     0.0   
11     12   47.0   1.0    1.0       0.0        1.0  0.0   0.0     0.0   
12     13   26.0   1.0    1.0       0.0        1.0  0.0   0.0     0.0   
13     14   37.0   0.0    0.0       1.0        0.0  2.0   0.0     1.0   
14     15   69.0   0.0    0.0       0.0        0.0  1.0   0.0     0.0   
15     16   37.0   2.0    0.0       0.0        0.0  1.0   0.0     0.0   
16     17   30.0   2.0    0.0       0.0        0.0  0.0   0.0     0.0   
17     18   37.0   0.0    0.0       0.0        3.0  0.0   0.0     0.0   
18     19   27.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
19     20   28.0   0.0    2.0       1.0        0.0  0.0   0.0     1.0   
20     21   64.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
21     22   98.0   3.0    1.0       1.0        0.0  0.0   0.0     0.0   
22     23   24.0   0.0    2.0       1.0        0.0  0.0   0.0     0.0   
23     24   51.0   1.0    2.0       0.0        0.0  1.0   0.0     0.0   
24     25   44.0   1.0    1.0       0.0        0.0  0.0   0.0     0.0   
25     26   53.0   1.0    0.0       1.0        0.0  1.0   1.0     0.0   
26     27   30.0   2.0    0.0       0.0        0.0  0.0   0.0     0.0   
27     28   33.0   2.0    0.0       0.0        0.0  0.0   0.0     0.0   
28     29   50.0   0.0    0.0       0.0        1.0  0.0   1.0     0.0   
29     30   38.0   2.0    0.0       1.0        0.0  1.0   0.0     1.0   
..    ...    ...   ...    ...       ...        ...  ...   ...     ...   
55     56   48.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
56     57   36.0   0.0    1.0       0.0        1.0  0.0   0.0     0.0   
57     58   51.0   1.0    0.0       1.0        0.0  1.0   0.0     0.0   
58     59   49.0   0.0    0.0       1.0        0.0  0.0   0.0     0.0   
59     60   53.0   0.0    0.0       0.0        0.0  1.0   0.0     1.0   
60     61   35.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
61     62   75.0   0.0    0.0       0.0        0.0  0.0   1.0     0.0   
62     63   58.0   4.0    0.0       0.0        1.0  1.0   1.0     0.0   
63     64   32.0   5.0    0.0       1.0        0.0  3.0   3.0     0.0   
64     65   44.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
65     66   48.0   0.0    0.0       1.0        0.0  1.0   2.0     0.0   
66     67   24.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
67     68   30.0   1.0    0.0       0.0        0.0  1.0   0.0     0.0   
68     69   66.0   0.0    1.0       4.0        0.0  0.0   2.0     6.0   
69     70   72.0   1.0    2.0       2.0        0.0  2.0   0.0     1.0   
70     71   45.0   0.0    1.0       1.0        0.0  2.0   0.0     0.0   
71     72   55.0   0.0    0.0       1.0        0.0  1.0   1.0     1.0   
72     73   64.0   0.0    1.0       2.0        0.0  0.0   2.0     0.0   
73     74   27.0   0.0    0.0       0.0        0.0  2.0   0.0     1.0   
74     75   52.0   1.0    0.0       0.0        0.0  1.0   0.0     0.0   
75     76   48.0   0.0    0.0       1.0        0.0  1.0   0.0     0.0   
76     77   62.0   0.0    1.0       0.0        0.0  1.0   0.0     0.0   
77     78   58.0   0.0    0.0       0.0        1.0  4.0   6.0 

In [120]:
DF=DF.rename(index=str,columns={"index": "Paper"})

In [121]:
DF=DF.merge(authors,how='inner')

In [122]:
sums=DF.groupby("Author").mean()

In [123]:
sumstrans=sums.T
sumtrans=sumstrans.drop('Paper',axis=0)

In [124]:
unknown

Paper             18    19    20    49    50    51    52    53    54    55  \
a               37.0  27.0  28.0  33.0  14.0  46.0  35.0  48.0  35.0  48.0   
able             0.0   0.0   0.0   2.0   0.0   1.0   1.0   0.0   0.0   0.0   
about            0.0   0.0   2.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
absolute         0.0   0.0   1.0   0.0   1.0   2.0   0.0   0.0   0.0   0.0   
according        3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   2.0   
act              0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
acts             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   
actual           0.0   0.0   1.0   0.0   0.0   0.0   0.0   2.0   0.0   0.0   
addition         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
additional       0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   
administration   1.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0   
admit            1.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   
admitted         0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   2.0   0.0   
advantage        0.0   0.0   0.0   2.0   1.0   0.0   2.0   0.0   1.0   0.0   
advantages       0.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0   2.0   0.0   
adversaries      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
affairs          0.0   0.0   1.0   0.0   0.0   0.0   0.0   5.0   0.0   1.0   
afford           0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
after            3.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
against          4.0   6.0   0.0   9.0   1.0   8.0   0.0   2.0   2.0   4.0   
agency           0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   
aid              1.0   2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
all              8.0   5.0   6.0   5.0   5.0  12.0   3.0   9.0   9.0   5.0   
almost           1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
alone            1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   1.0   
already          1.0   0.0   2.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
also             0.0   0.0   2.0   1.0   1.0   0.0   2.0   4.0   1.0   1.0   
altogether       0.0   1.0   0.0   1.0   0.0   2.0   0.0   1.0   0.0   0.0   
always           1.0   0.0   1.0   1.0   0.0   0.0   1.0   0.0   0.0   1.0   
am               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   
...              ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
views            0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   
violent          0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   
want             0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
war              2.0   2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   
was             29.0  13.0   7.0   1.0   3.0   1.0  11.0   4.0   1.0   2.0   
we               3.0   1.0   2.0   4.0   1.0   2.0   5.0   4.0   3.0   6.0   
weight           0.0   1.0   1.0   0.0   0.0   1.0   0.0   0.0   2.0   2.0   
well             1.0   1.0   1.0   2.0   1.0   4.0   3.0   4.0   2.0   2.0   
were            15.0   5.0   0.0   1.0   1.0   4.0  10.0   4.0   6.0   6.0   
what             0.0   1.0   1.0   0.0   0.0   2.0   2.0   4.0   2.0   3.0   
whatever         1.0   1.0   0.0   0.0   0.0   1.0   0.0   1.0   1.0   1.0   
when             5.0   0.0   3.0   2.0   2.0   0.0   3.0   1.0   5.0   1.0   
where            1.0   1.0   3.0   0.0   1.0   2.0   1.0   6.0   0.0   4.0   
whether          0.0   0.0   1.0   1.0   3.0   0.0   4.0   1.0   1.0   3.0   
which           12.0  31.0  12.0  20.0   9.0  14.0  20.0  23.0  25.0  28.0   
while            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
who              8.0   5.0   3.0   4.0   2.0   1.0   0.0   4.0   5.0   3.0   
whole            2.0   1.0   1.0   2.0   0.0   3.0   1.0   0.0   0.0   4.0   
wholly           1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
whom             1.0  

In [142]:
unknown=DF[pd.isnull(DF['Author'])]
known=DF[~pd.isnull(DF['Author'])]
unknown.head()

Paper     a  able  about  absolute  according  act  acts  actual  \
17     18  37.0   0.0    0.0       0.0        3.0  0.0   0.0     0.0   
18     19  27.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0   
19     20  28.0   0.0    2.0       1.0        0.0  0.0   0.0     1.0   
48     49  33.0   2.0    0.0       0.0        0.0  0.0   0.0     0.0   
49     50  14.0   0.0    0.0       1.0        0.0  0.0   0.0     0.0   

    addition   ...    will  with  within  without  would  years  yet  york  \
17       0.0   ...     1.0  12.0     0.0      0.0    6.0    0.0  0.0   0.0   
18       0.0   ...     1.0  20.0     1.0      1.0    4.0    0.0  0.0   0.0   
19       0.0   ...     3.0   8.0     1.0      3.0    1.0    0.0  1.0   0.0   
48       0.0   ...     1.0  11.0     2.0      2.0   21.0    0.0  0.0   0.0   
49       0.0   ...     7.0   5.0     6.0      3.0   11.0    0.0  0.0   0.0   

    you  Author  
17  0.0     NaN  
18  0.0     NaN  
19  0.0     NaN  
48  0.0     NaN  
49  0.0     NaN  

[5 rows x 641 columns]

In [143]:
unknown=unknown.drop("Author",axis=1).set_index("Paper").T
known=known.drop("Author",axis=1).set_index("Paper").T

In [74]:
knowns=DF[~pd.isnull(DF['Author'])]

In [75]:
knowns=knowns.set_index("Paper")
knowns['AuthorNumeric']=1
knowns.loc[knowns['Author']=='Madison','AuthorNumeric']=2
knowns.loc[knowns['Author']=='Jay','AuthorNumeric']=3


In [127]:
from sklearn.linear_model import Lasso
model=Lasso()
model.fit(knowns[knowns.columns.difference(['Author', 'AuthorNumeric'])],knowns['AuthorNumeric'])

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [128]:
model.predict(unknown[unknown.columns.difference(['Paper','Author'])])

ValueError: shapes (639,15) and (639,) not aligned: 15 (dim 1) != 639 (dim 0)

In [85]:
knowns.head()

a  able  about  absolute  according  act  acts  actual  addition  \
Paper                                                                        
1      25.0   1.0    0.0       0.0        0.0  1.0   0.0     0.0       0.0   
2      29.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0       0.0   
3      13.0   1.0    0.0       0.0        0.0  1.0   0.0     0.0       0.0   
4      16.0   0.0    0.0       2.0        0.0  1.0   0.0     0.0       0.0   
5       9.0   0.0    0.0       0.0        0.0  0.0   0.0     0.0       0.0   

       additional      ...        with  within  without  would  years  yet  \
Paper                  ...                                                   
1             1.0      ...         6.0     0.0      0.0    2.0    0.0  0.0   
2             0.0      ...        13.0     0.0      2.0    5.0    0.0  3.0   
3             0.0      ...        10.0     0.0      0.0    2.0    1.0  3.0   
4             0.0      ...        12.0     0.0      2.0   14.0    0.0  0.0   
5             0.0      ...        11.0     1.0      1.0   35.0    1.0  3.0   

       york  you    Author  AuthorNumeric  
Paper                                      
1       0.0  7.0  Hamilton              1  
2       0.0  0.0       Jay              3  
3       0.0  0.0       Jay              3  
4       0.0  1.0       Jay              3  
5       0.0  1.0       Jay              3  

[5 rows x 641 columns]

In [129]:
sumtrans

Author           Hamilton   Jay    Madison
a               48.941176  19.8  54.857143
able             0.725490   1.2   0.785714
about            0.411765   0.0   0.071429
absolute         0.509804   0.6   0.571429
according        0.392157   0.0   1.571429
act              0.568627   1.0   1.500000
acts             0.450980   0.6   0.642857
actual           0.333333   0.0   0.428571
addition         0.392157   0.0   0.285714
additional       0.431373   0.0   0.428571
administration   0.647059   0.0   0.571429
admit            0.607843   0.4   0.500000
admitted         0.254902   0.0   0.642857
advantage        0.607843   0.8   1.000000
advantages       0.450980   0.4   0.357143
adversaries      0.333333   0.0   0.642857
affairs          0.196078   1.0   0.142857
afford           0.509804   0.6   0.071429
after            0.490196   0.2   0.500000
against          3.254902   3.0   6.071429
agency           0.431373   0.0   0.500000
aid              0.392157   0.2   0.142857
all              7.725490   4.6   9.642857
almost           0.490196   0.4   0.714286
alone            0.509804   0.0   0.571429
already          0.823529   0.2   0.571429
also             0.549020   2.2   1.071429
altogether       0.411765   0.0   0.500000
always           1.215686   1.6   0.500000
am               0.470588   0.2   0.357143
...                   ...   ...        ...
views            0.529412   0.0   0.714286
violent          0.372549   0.0   0.428571
want             0.666667   0.8   0.428571
war              0.666667   2.2   0.714286
was              2.960784   2.8   5.285714
we               5.921569   4.8   5.285714
weight           0.647059   0.4   0.571429
well             1.960784   4.6   2.714286
were             2.803922   2.8   5.142857
what             2.784314   1.8   3.000000
whatever         0.549020   1.4   0.357143
when             2.098039   2.8   1.285714
where            1.686275   0.4   2.428571
whether          0.862745   2.4   2.071429
which           22.960784  10.8  29.357143
while            0.686275   0.4   0.000000
who              4.725490   6.4   5.000000
whole            0.960784   1.0   2.000000
wholly           0.392157   0.0   0.785714
whom             0.686275   2.0   0.642857
whose            0.941176   0.8   1.071429
will            12.960784  14.2  16.785714
with            11.882353  12.0  15.071429
within           0.921569   0.2   2.428571
without          2.235294   1.4   3.571429
would           17.549020  12.4  11.071429
years            0.176471   0.4   0.214286
yet              1.313725   2.6   1.571429
york             0.470588   0.0   0.285714
you              0.372549   0.4   0.642857

[639 rows x 3 columns]

In [131]:
#unknown=unknown.set_index('Paper').drop('Author',axis=1)
unknown

Paper             18    19    20    49    50    51    52    53    54    55  \
a               37.0  27.0  28.0  33.0  14.0  46.0  35.0  48.0  35.0  48.0   
able             0.0   0.0   0.0   2.0   0.0   1.0   1.0   0.0   0.0   0.0   
about            0.0   0.0   2.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
absolute         0.0   0.0   1.0   0.0   1.0   2.0   0.0   0.0   0.0   0.0   
according        3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   2.0   
act              0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
acts             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   
actual           0.0   0.0   1.0   0.0   0.0   0.0   0.0   2.0   0.0   0.0   
addition         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
additional       0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   
administration   1.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0   
admit            1.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   
admitted         0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   2.0   0.0   
advantage        0.0   0.0   0.0   2.0   1.0   0.0   2.0   0.0   1.0   0.0   
advantages       0.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0   2.0   0.0   
adversaries      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
affairs          0.0   0.0   1.0   0.0   0.0   0.0   0.0   5.0   0.0   1.0   
afford           0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
after            3.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
against          4.0   6.0   0.0   9.0   1.0   8.0   0.0   2.0   2.0   4.0   
agency           0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   
aid              1.0   2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
all              8.0   5.0   6.0   5.0   5.0  12.0   3.0   9.0   9.0   5.0   
almost           1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
alone            1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0   1.0   1.0   
already          1.0   0.0   2.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
also             0.0   0.0   2.0   1.0   1.0   0.0   2.0   4.0   1.0   1.0   
altogether       0.0   1.0   0.0   1.0   0.0   2.0   0.0   1.0   0.0   0.0   
always           1.0   0.0   1.0   1.0   0.0   0.0   1.0   0.0   0.0   1.0   
am               0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   
...              ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
views            0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   
violent          0.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   
want             0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
war              2.0   2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   
was             29.0  13.0   7.0   1.0   3.0   1.0  11.0   4.0   1.0   2.0   
we               3.0   1.0   2.0   4.0   1.0   2.0   5.0   4.0   3.0   6.0   
weight           0.0   1.0   1.0   0.0   0.0   1.0   0.0   0.0   2.0   2.0   
well             1.0   1.0   1.0   2.0   1.0   4.0   3.0   4.0   2.0   2.0   
were            15.0   5.0   0.0   1.0   1.0   4.0  10.0   4.0   6.0   6.0   
what             0.0   1.0   1.0   0.0   0.0   2.0   2.0   4.0   2.0   3.0   
whatever         1.0   1.0   0.0   0.0   0.0   1.0   0.0   1.0   1.0   1.0   
when             5.0   0.0   3.0   2.0   2.0   0.0   3.0   1.0   5.0   1.0   
where            1.0   1.0   3.0   0.0   1.0   2.0   1.0   6.0   0.0   4.0   
whether          0.0   0.0   1.0   1.0   3.0   0.0   4.0   1.0   1.0   3.0   
which           12.0  31.0  12.0  20.0   9.0  14.0  20.0  23.0  25.0  28.0   
while            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
who              8.0   5.0   3.0   4.0   2.0   1.0   0.0   4.0   5.0   3.0   
whole            2.0   1.0   1.0   2.0   0.0   3.0   1.0   0.0   0.0   4.0   
wholly           1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
whom             1.0  

In [132]:
from sklearn.linear_model import LinearRegression


In [133]:
model=LinearRegression()
model.fit(sumtrans[['Jay','Hamilton','Madison']],unknown[18])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [134]:
model.coef_

array([-0.07121786, -0.56081371,  1.27107459])

In [140]:
for j in unknown.columns:
    print(j)
    model.fit(sumtrans[['Hamilton','Jay','Madison']],unknown[j])
    print(model.coef_)

18
[-0.56081371 -0.07121786  1.27107459]
19
[-0.34928372  0.09161397  0.95511578]
20
[-0.11694914  0.12301544  0.52337235]
49
[ 0.16880277 -0.07475354  0.52525647]
50
[-0.03070287  0.0965857   0.34630161]
51
[ 0.02641425 -0.21814016  0.78383491]
52
[ 0.26574421 -0.14310385  0.51218737]
53
[ 0.26510006  0.08827219  0.48286135]
54
[ 0.25590081 -0.17825776  0.60274525]
55
[ 0.53480484  0.05624338  0.24223033]
56
[ 0.29123313  0.07798419  0.30668463]
57
[ 0.27899005 -0.01767253  0.59071119]
58
[ 0.1948211  -0.1328159   0.65961841]
62
[ 0.60935036  0.1885121   0.21974136]
63
[ 0.27377509 -0.16167085  0.90256461]


In [144]:
for j in known.columns:
    print(j)
    model.fit(sumtrans[['Hamilton','Jay','Madison']],known[j])
    print(model.coef_)

1
[ 0.70897823  0.16095975 -0.09400813]
2
[ -2.09350917e-05   9.14374279e-01   5.28353095e-02]
3
[ 0.03345922  0.77834283  0.01090834]
4
[-0.14591144  1.17433278 -0.01789665]
5
[ 0.14802777  0.97053536 -0.24011422]
6
[ 0.59724056  0.20608698  0.19943642]
7
[ 1.03928852 -0.11452092  0.03057101]
8
[ 0.96343842  0.17844735 -0.17997071]
9
[ 0.90311373 -0.07874026  0.01663123]
10
[-0.04355953  0.56934486  0.76523478]
11
[ 1.46874864  0.28176742 -0.46927905]
12
[ 0.96439324  0.16840334 -0.11780631]
13
[ 0.59304115  0.02824435 -0.17537903]
14
[ 0.15376392  0.13857476  0.55925603]
15
[ 1.40593449  0.0583393  -0.11549168]
16
[ 1.15515447 -0.03105457 -0.1499769 ]
17
[ 0.39960134 -0.0114114   0.28148226]
21
[ 0.8255204  -0.22629347  0.17599298]
22
[ 1.95009495  0.03385471 -0.34048727]
23
[ 0.43932017  0.1580522   0.25128766]
24
[ 1.20268477  0.35762594 -0.46718065]
25
[ 0.93889118  0.12791361 -0.10731593]
26
[ 1.26700946  0.05829553 -0.22423057]
27
[ 0.51808654  0.00370056  0.14047752]
28
[ 0.605

Paper             1     2     3     4     5     6     7     8     9     10  \
a               25.0  29.0  13.0  16.0   9.0  52.0  48.0  45.0  46.0  78.0   
able             1.0   0.0   1.0   0.0   0.0   0.0   2.0   2.0   3.0   2.0   
about            0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
absolute         0.0   0.0   0.0   2.0   0.0   0.0   0.0   1.0   1.0   0.0   
according        0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   3.0   
act              1.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   3.0   
acts             0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   
actual           0.0   0.0   0.0   0.0   0.0   1.0   2.0   0.0   0.0   0.0   
addition         0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
additional       1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
administration   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   
admit            1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   
admitted         0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
advantage        0.0   0.0   1.0   0.0   0.0   1.0   1.0   2.0   0.0   2.0   
advantages       1.0   0.0   0.0   2.0   0.0   1.0   1.0   0.0   3.0   1.0   
adversaries      0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   
affairs          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
afford           1.0   0.0   1.0   0.0   0.0   0.0   2.0   0.0   0.0   0.0   
after            2.0   1.0   0.0   0.0   0.0   3.0   0.0   1.0   0.0   0.0   
against          2.0   1.0   3.0   6.0   5.0   4.0   1.0   5.0   4.0   5.0   
agency           0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   
aid              0.0   0.0   0.0   0.0   1.0   0.0   0.0   2.0   0.0   0.0   
all              7.0   4.0   4.0   3.0   4.0   6.0   8.0   8.0   7.0   4.0   
almost           0.0   1.0   0.0   0.0   1.0   2.0   0.0   1.0   1.0   1.0   
alone            0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   
already          2.0   0.0   1.0   0.0   0.0   2.0   0.0   0.0   1.0   0.0   
also             0.0   2.0   3.0   2.0   2.0   0.0   0.0   0.0   1.0   0.0   
altogether       0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
always           1.0   1.0   4.0   0.0   1.0   0.0   0.0   3.0   0.0   2.0   
am               3.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
...              ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
views            0.0   0.0   0.0   0.0   0.0   2.0   1.0   0.0   1.0   3.0   
violent          0.0   0.0   0.0   0.0   0.0   3.0   0.0   1.0   0.0   2.0   
want             0.0   0.0   2.0   1.0   0.0   1.0   0.0   1.0   0.0   0.0   
war              0.0   0.0   5.0   5.0   1.0   6.0   1.0   4.0   0.0   0.0   
was              0.0   8.0   0.0   1.0   3.0  11.0   7.0   1.0   2.0   2.0   
we               7.0   5.0   0.0  10.0   4.0   3.0  16.0   5.0   6.0   9.0   
weight           0.0   0.0   2.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
well             3.0   4.0   7.0   4.0   1.0   6.0   2.0   0.0   2.0   4.0   
were             1.0   7.0   1.0   0.0   6.0  10.0   9.0   0.0  10.0   0.0   
what             0.0   2.0   0.0   5.0   2.0   2.0   3.0   0.0   0.0   5.0   
whatever         1.0   1.0   0.0   2.0   2.0   0.0   1.0   1.0   0.0   0.0   
when             1.0   4.0   1.0   3.0   1.0   0.0   1.0   0.0   1.0   2.0   
where            0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   2.0   
whether          2.0   1.0   3.0   2.0   2.0   2.0   0.0   0.0   0.0   2.0   
which           18.0  10.0  11.0  10.0  10.0  23.0  22.0  26.0  25.0  38.0   
while            0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   
who              8.0   7.0   1.0   3.0   3.0   8.0   2.0   0.0   3.0   9.0   
whole            0.0   0.0   0.0   2.0   1.0   0.0   1.0   1.0   0.0   2.0   
wholly           0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0   0.0   
whom             0.0  